import test from 'node:test';
import assert from 'node:assert/strict';
import {refine,getTowns,slug,escape} from '../scripts/refine.mjs';
const province={slug:'bizkaia',name:'Bizkaia'},town={name:'Zalla',slug:'zalla',provinceSlug:'bizkaia',path:'/bizkaia/zalla/'};
const context={route:'/',domain:'https://preview.example.invalid',prod:false,wa:'',provinces:[province],towns:[town]};
const page=(heading='Limpieza de canalones')=>`<!doctype html><html lang="es"><head><title>Canalones Limpios</title><meta name="description" content="Canalones y bajantes"><meta name="robots" content="index,follow"><link rel="canonical" href="https://old.example.invalid/"><meta property="og:title" content="Canalones Limpios"><meta property="og:description" content="Canalones y bajantes"><meta property="og:url" content="https://old.example.invalid/"><script type="application/ld+json">{}</script></head><body><header><nav class="nav"></nav></header><main><section class="hero"><div class="wrap hero-grid"><div><h1>${heading}</h1></div><div class="hero-art"><img src="test.jpg"></div></div></section><section id="servicios"><div class="services"><article class="card"><b>Limpieza de canalones</b><p>Retirada de residuos.</p></article></div></section><section class="section visual-section"><p>Ilustraciones antiguas.</p></section><section class="section wrap" id="pueblos"><div class="home-town-groups"></div></section><section class="section wrap" id="contacto"><a href="#contacto">Consultar</a></section></main></body></html>`;
const graph=h=>JSON.parse(h.match(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/)[1])['@graph'];
test('escape y slugs mantienen rutas históricas',()=>{assert.equal(slug('Urduña/Orduña'),'urduna-orduna');assert.equal(escape('A & "B"'),'A &amp; &quot;B&quot;')});
test('inventario independiente del manifiesto',()=>{assert.equal(getTowns({provinces:[province]},{groups:{bizkaia:[{name:'Zalla',id:'069'}]}})[0].path,'/bizkaia/zalla/')});
test('portada conserva H1 e incorpora bloques y foto acreditada',()=>{const h=refine(page('Limpieza de canalones y tejados cerca de tu pueblo'),context);for(const s of ['<h1>Limpieza de canalones y tejados cerca de tu pueblo</h1>','id="viviendas-comunidades"','id="incluye"','data-town-search','id="presupuesto"','id="resumen"','24 h','urgencias','Chris Shafer','srcset='])assert.ok(h.includes(s),s);assert.ok(!h.includes('Ilustraciones antiguas.'))});
test('HTML contiene enlaces y contenido sin depender de JS',()=>{const h=refine(page(),context);assert.ok(h.includes('Comunidades de propietarios'));assert.ok(h.includes('data-wa-mini'))});
test('localidad en consulta y breadcrumbs exactos',()=>{const ctx={...context,route:town.path,town,province};const h=refine(page(),ctx);assert.ok(h.includes('value="Zalla"'));assert.ok(h.includes('Limpieza de canalones en Zalla, Bizkaia'));assert.ok(h.includes('<h3>Limpieza de canalones en Zalla</h3>'));assert.ok(h.includes('<h3>Limpieza de tejados en Zalla</h3>'));assert.deepEqual(graph(h).find(x=>x['@type']==='BreadcrumbList').itemListElement.map(x=>x.item),['https://preview.example.invalid/','https://preview.example.invalid/bizkaia/','https://preview.example.invalid/bizkaia/zalla/'])});
test('404 no indexable incluso en producción',()=>{const h=refine(page('Página no encontrada'),{...context,route:'/404.html',prod:true});assert.ok(h.includes('content="noindex,nofollow"'));assert.ok(h.includes('href="https://preview.example.invalid/404.html"'));assert.ok(!graph(h).some(x=>x['@type']==='Service'))});
test('metadatos de producción, mini WhatsApp y servicio de tejados',()=>{const h=refine(page(),{...context,prod:true,phone:'123 456 789',tel:'+34123456789',wa:'34123456789'});assert.ok(h.includes('content="index,follow"'));assert.ok(h.includes('href="tel:+34123456789"'));assert.ok(h.includes('data-whatsapp="34123456789"'));assert.ok(h.includes('data-wa-mini'));assert.ok(h.includes('Abrir WhatsApp'));assert.ok(h.includes('id="servicio-limpieza-de-tejados"'));assert.ok(!/aggregateRating|reviewCount|ratingValue/.test(h))});
test('protección de datos en atributos y JSON-LD',()=>{const h=refine(page(),{...context,town:{...town,name:'A & B </script>'},province,route:town.path});assert.ok(h.includes('A &amp; B &lt;/script&gt;'));assert.ok(!h.includes('B </script>'));assert.doesNotThrow(()=>graph(h))});
test('no aplica dos veces ni acepta galería de estructura desconocida',()=>{const h=refine(page(),context);assert.throws(()=>refine(h,context),/ya se ha aplicado/);assert.throws(()=>refine(page().replace('class="section visual-section"','class="otro"'),context),/galería inicial/)});

test('no aparecen mensajes de preview o maqueta en la portada',()=>{const h=refine(page('Limpieza de canalones y tejados cerca de tu pueblo'),context);assert.ok(!/vista previa|pendiente de publicar|contacto comercial|servicio organizado por pueblos|preparar una consulta|consulta guiada/i.test(h))});

test('páginas legales no reciben bloques comerciales',()=>{for(const route of ['/aviso-legal/','/privacidad/','/cookies/']){const h=refine(page('Información legal'),{...context,route});assert.ok(!h.includes('data-wa-mini'));assert.ok(!graph(h).some(x=>x['@type']==='Service'))}});
