import fs from 'node:fs';
import path from 'node:path';
import {getTowns,serviceNames,slug} from './refine.mjs';
const root='dist',site=JSON.parse(fs.readFileSync('config/site.json','utf8')),data=JSON.parse(fs.readFileSync('.cache/municipios.json','utf8')),manifest=JSON.parse(fs.readFileSync(root+'/manifest.json','utf8'));
const towns=getTowns(site,data),prod=process.env.BUILD_MODE==='production',domain=prod?(process.env.SITE_DOMAIN||site.productionDomain):site.previewDomain,errors=[];
const expect=(condition,message)=>{if(!condition)errors.push(message)};
const decode=s=>String(s).replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&amp;/g,'&');
const legalRoutes=['/aviso-legal/','/privacidad/','/cookies/'],serviceRoutes=['/limpieza-canalones/','/limpieza-tejados/','/desatasco-bajantes/','/reparacion-goteras/','/impermeabilizacion-tejados/'];const routes=['/',...serviceRoutes,...legalRoutes,...site.provinces.map(p=>`/${p.slug}/`),...towns.map(t=>t.path)];
const fileFor=route=>route==='/'?'index.html':route.endsWith('/')?route.slice(1)+'index.html':route.slice(1);
const walk=d=>fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(d,e.name)):[path.join(d,e.name)]);
const html=new Map(walk(root).filter(f=>f.endsWith('.html')).map(f=>[path.relative(root,f).split(path.sep).join('/'),fs.readFileSync(f,'utf8')]));
expect(new Set(routes).size===routes.length,'Rutas repetidas en el dataset');
expect(manifest.towns===towns.length,'Manifiesto: municipios no coinciden con dataset');
expect(manifest.provinces===site.provinces.length,'Manifiesto: provincias no coinciden con configuración');
expect(manifest.urls===routes.length,'Manifiesto: URLs no coinciden con rutas esperadas');
expect(manifest.mode===(prod?'production':'preview'),'Modo de publicación incoherente');
expect(html.size===routes.length+1,'Número de HTML incorrecto, incluyendo 404');
const titles=new Set(),metas=new Set(),canonicals=new Set();let links=0,contacts=0,breadcrumbs=0;
for(const route of [...routes,'/404.html']){
  const file=fileFor(route),h=html.get(file);expect(Boolean(h),`Falta ${file}`);if(!h)continue;
  const is404=route==='/404.html',isLegal=legalRoutes.includes(route),isService=serviceRoutes.includes(route);
  expect(h.includes('data-refined="1"'),file+': falta fase de presentación');
  expect([...h.matchAll(/<h1\b/g)].length===1,file+': H1 ausente o duplicado');
  expect(h.includes(`name="robots" content="${prod&&!is404?'index,follow':'noindex,nofollow'}"`),file+': robots incorrecto');
  const ids=[...h.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);expect(new Set(ids).size===ids.length,file+': IDs duplicados');
  const title=decode(h.match(/<title>([\s\S]*?)<\/title>/)?.[1]||''),desc=decode(h.match(/<meta name="description" content="([^"]*)"/)?.[1]||''),canonical=decode(h.match(/<link rel="canonical" href="([^"]*)"/)?.[1]||'');
  expect(Boolean(title&&desc&&canonical),file+': metadatos incompletos');expect(canonical===new URL(route,domain).href,file+': canonical incorrecto');
  if(!is404){for(const [seen,value,key]of [[titles,title,'title'],[metas,desc,'description'],[canonicals,canonical,'canonical']]){expect(!seen.has(value),file+': '+key+' duplicado');seen.add(value)}}
  for(const [key,value]of [['title',title],['description',desc],['url',canonical]])expect(decode(h.match(new RegExp(`<meta property="og:${key}" content="([^"]*)"`))?.[1]||'')===value,file+': Open Graph incoherente '+key);
  try{const data=JSON.parse(h.match(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/)?.[1]||'');const graph=data['@graph'];expect(Array.isArray(graph),file+': falta grafo');const page=graph.find(x=>['WebPage','CollectionPage'].includes(x['@type']));expect(page?.url===canonical&&page?.description===desc,file+': datos estructurados no coinciden');expect(!/aggregateRating|reviewCount|ratingValue/.test(JSON.stringify(data)),file+': valoración no acreditada');if(route!=='/'&&!is404&&!isLegal){const crumb=graph.find(x=>x['@type']==='BreadcrumbList');const expected=isService?['/',route]:['/',...route.split('/').filter(Boolean).map((_,i,a)=>'/'+a.slice(0,i+1).join('/')+'/')];expect(crumb?.itemListElement.length===expected.length&&crumb.itemListElement.every((v,i)=>v.item===new URL(expected[i],domain).href&&v.position===i+1),file+': breadcrumbs incorrectos');breadcrumbs++}}
  catch(error){errors.push(file+': JSON-LD inválido '+error.message)}
  for(const m of h.matchAll(/href="([^"]+)"/g)){const href=decode(m[1]);if(!href.startsWith('/')&&!href.startsWith('#'))continue;const url=new URL(href,canonical);if(url.origin!==new URL(domain).origin)continue;const target=fileFor(url.pathname);expect(fs.existsSync(path.join(root,target)),file+': enlace inexistente '+href);if(url.hash&&html.has(target))expect(html.get(target).includes(`id="${decodeURIComponent(url.hash.slice(1))}"`),file+': ancla inexistente '+href);links++;}
  for(const m of h.matchAll(/(?:src|href)="(\/assets\/[^"?#]+)/g))expect(fs.existsSync(path.join(root,m[1].slice(1))),file+': recurso ausente '+m[1]);
  if(!is404&&!isLegal){expect(h.includes('id="contacto"'),file+': contacto sin destino');expect(h.includes('class="contact-panel wa-panel"'),file+': falta bloque de contacto profesional');expect(h.includes('data-wa-mini'),file+': falta mini formulario WhatsApp');contacts++}
  expect(!/vista previa|pendiente de publicar|contacto comercial|servicio organizado por pueblos|preparar una consulta|consulta guiada/i.test(h),file+': conserva texto de maqueta o preview');expect(!/\d{3}\s*\d{2}\s*\d{2}\s*\d{2}WhatsApp/i.test(h),file+': teléfono pegado a WhatsApp');expect(h.includes('class="mobilebar" data-nosnippet'),'Barra móvil de contacto debe quedar fuera del snippet');expect(!/Canalones Limpios/.test(h),file+': conserva marca antigua');
}
for(const town of towns){const h=html.get(fileFor(town.path))||'',safeTown=town.name.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));expect(h.includes(`<title>Limpieza de canalones y tejados en ${safeTown} | \${site.phone}</title>`),town.path+': title local incompleto');expect(h.includes(`Urgencias de canalones, goteras y tejados en ${safeTown}`),town.path+': falta urgencias locales');for(const service of serviceNames){expect(h.includes(`id="servicio-${slug(service)}"`),town.path+': falta servicio '+service);expect(h.includes(`<h3>${service} en ${safeTown}</h3>`),town.path+': servicio sin localidad '+service)}expect(h.includes(`value="${safeTown}"`),town.path+': mini WhatsApp pierde localidad');}
const home=html.get('index.html')||'';expect(home.includes('<h1>Limpieza de canalones y tejados cerca de tu pueblo</h1>'),'H1 aprobado alterado');for(const id of ['pueblos','presupuesto','viviendas-comunidades','cubiertas','resumen','contacto'])expect(home.includes(`id="${id}"`),'Portada: falta '+id);expect(home.includes('★★★★★'),'Se han perdido las estrellas decorativas');expect(home.includes('data-town-search'),'Falta buscador de pueblos');expect(home.includes('24 h')&&home.includes('urgencias'),'Falta urgencias 24 h');expect(home.includes(`<title>Limpieza de canalones y tejados | \${site.phone}</title>`),'Title portada SEO incorrecto');expect(home.includes(towns.length.toLocaleString('es-ES')),'Resumen no muestra total de municipios');for(const legal of legalRoutes)expect(fs.existsSync(path.join(root,fileFor(legal))),'Falta legal '+legal);expect(home.includes('data-cookie-banner')&&home.includes('data-cookie-reject')&&home.includes('data-cookie-accept'),'Falta banner de cookies');
const search=JSON.parse(fs.readFileSync(root+'/assets/towns.json','utf8'));expect(search.length===towns.length,'Buscador: inventario incompleto');expect(new Set(search.map(t=>t.path)).size===towns.length,'Buscador: rutas repetidas');
if(prod){const children=walk(root+'/sitemaps').filter(f=>f.endsWith('.xml'));const sitemapUrls=children.flatMap(f=>[...fs.readFileSync(f,'utf8').matchAll(/<loc>([^<]+)<\/loc>/g)].map(m=>decode(m[1])));const expected=new Set(routes.map(r=>new URL(r,domain).href));expect(sitemapUrls.length===expected.size&&new Set(sitemapUrls).size===expected.size&&sitemapUrls.every(u=>expected.has(u)),'Sitemaps incompletos o con URLs ajenas');}
else{expect(!fs.existsSync(root+'/sitemap.xml'),'Preview con sitemap');expect(fs.readFileSync(root+'/_headers','utf8').includes('/*\n  X-Robots-Tag: noindex, nofollow'),'Preview sin noindex HTTP');}
if(errors.length){console.error('AUDITORÍA FINAL FALLIDA:',errors.length);for(const error of errors.slice(0,80))console.error('- '+error);process.exit(1)}
const report={mode:manifest.mode,municipalities:towns.length,provinces:site.provinces.length,urls:routes.length,html:html.size,checkedInternalLinks:links,contacts,breadcrumbs,serviceHubs:serviceRoutes.length,legalPages:legalRoutes.length,cookieConsent:true,externalImages:2,editorialStatus:'Contenido local comparte bloques. Pendiente validación de cobertura, datos comerciales y valor editorial por localidad; no se certifica originalidad ni posicionamiento.'};
fs.writeFileSync(root+'/quality-report.json',JSON.stringify(report,null,2));console.log('AUDITORÍA FINAL OK:',JSON.stringify(report));
