import fs from'node:fs';import path from'node:path';import site from'../config/site.json'with{type:'json'};
const prod=process.env.BUILD_MODE==='production',domain=prod?(process.env.SITE_DOMAIN||site.productionDomain):site.previewDomain,phone=prod?(process.env.SITE_PHONE||site.phone||''):'',tel=prod?(process.env.SITE_TEL||site.tel||''):'',wa=prod?(process.env.SITE_WHATSAPP||site.whatsapp||''):'';
if(prod&&!domain)throw Error('Producción requiere un dominio válido');
const data=JSON.parse(fs.readFileSync('.cache/municipios.json','utf8')),out='dist';fs.rmSync(out,{recursive:true,force:true});fs.mkdirSync(out,{recursive:true});fs.mkdirSync(out+'/assets',{recursive:true});
for(const f of ['site.css','site.js','hero-canalones.svg','limpieza-hojas.svg','bajante-atascada.svg','reparacion-canalon.svg','favicon.svg'])fs.copyFileSync('src/'+f,out+'/assets/'+f);
const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),N=s=>String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase(),S=s=>N(s).replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''),U=r=>new URL(r,domain.endsWith('/')?domain:domain+'/').href;
const logo='<span class="brand brand-wordmark"><span class="brand-kicker">LIMPIEZA</span><span class="brand-main">CANALONES Y TEJADOS</span><span class="brand-rule" aria-hidden="true"></span><small>Canalones · Bajantes · Goteras · Cubiertas</small></span>';
const contact=()=>phone?`<div class="actions"><a class="btn" href="tel:${E(tel)}">☎ ${E(phone)}</a><a class="btn whatsapp-btn" href="https://wa.me/${E(wa)}">WhatsApp</a></div>`:'<div class="actions"><a class="btn" href="#contacto">Consultar servicio</a></div>';
const header=()=>`<div class="top"><div class="wrap"><span>Limpieza y mantenimiento de canalones</span><span><strong class="top-urgent-dot" aria-hidden="true"></strong> Urgencias 24 h · <a href="tel:${E(tel)}">${E(phone)}</a> · Canalones · Tejados · Bajantes</span></div></div><header><div class="wrap head"><a href="/">${logo}</a><nav class="nav"><a href="/#servicios">Servicios</a><a href="/#zonas">Provincias</a><a href="/#contacto">Contacto</a></nav></div></header>`;
const footer=()=>`<footer class="footer"><div class="wrap footer-grid"><div><strong>Limpieza Canalones y Tejados</strong><p>Limpieza, desatasco y mantenimiento de canalones y bajantes.</p><p class="fine legal-links">${legalLinks}</p></div><div><strong>Provincias</strong><p>${site.provinces.map(p=>`<a href="/${p.slug}/">${E(p.name)}</a>`).join(' · ')}</p></div><div><strong>Contacto</strong><p>${phone?E(phone):'Consulta el servicio desde tu localidad'}</p></div></div></footer>${cookieUi()}${phone?`<div class="mobilebar"><a href="tel:${E(tel)}">☎ ${E(phone)}</a><a href="https://wa.me/${E(wa)}">WhatsApp</a></div>`:''}`;
const head=(title,desc,route,area)=>`<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>${E(title)}</title><meta name="description" content="${E(desc)}"><meta name="robots" content="${prod?'index,follow':'noindex,nofollow'}"><link rel="canonical" href="${E(U(route))}"><meta property="og:title" content="${E(title)}"><meta property="og:description" content="${E(desc)}"><meta property="og:url" content="${E(U(route))}"><meta name="theme-color" content="#2f3133"><link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/assets/site.css"><script src="/assets/site.js" defer></script><script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@graph':[{'@type':'WebPage',name:title,url:U(route)},{'@type':'Service',name:'Limpieza y mantenimiento de canalones',areaServed:{'@type':'AdministrativeArea',name:area},provider:{'@type':'Organization',name:'Limpieza Canalones y Tejados',url:U('/')}}]})}</script></head>`;
const services=[['Limpieza de canalones','Retirada de hojas, tierra, musgo y residuos para recuperar el paso del agua.'],['Desatasco de bajantes','Localización y liberación de obstrucciones cuando el agua rebosa o evacua lentamente.'],['Reparación de canalones','Revisión de uniones, fijaciones, sellados, pendientes y pequeños tramos deteriorados.'],['Sustitución de tejas rotas','Cambio puntual de tejas desplazadas, fisuradas o rotas cuando el acceso y el estado de la cubierta lo permiten.'],['Reparación de goteras','Localización de puntos de entrada de agua en cubierta, encuentros, limas y remates visibles.'],['Impermeabilización','Sellado e impermeabilización localizada de encuentros, remates y zonas expuestas a filtraciones.'],['Revisión de chimeneas','Comprobación de remates, encuentros y sellados alrededor de chimeneas y salidas en cubierta.'],['Mantenimiento preventivo','Limpiezas periódicas para reducir atascos, desbordamientos y humedades asociadas.'],['Mallas antihojas','Valoración de protectores cuando hay árboles próximos o acumulaciones frecuentes.'],['Revisión del sistema de evacuación','Comprobación visual de canalón, bajante y puntos de descarga durante el acceso.']];
const cards=()=>`<div class="services">${services.map(x=>`<article class="card"><b>${x[0]}</b><p>${x[1]}</p></article>`).join('')}</div>`;
const serviceHubs=[
  {slug:'limpieza-canalones',title:'Limpieza de canalones',desc:'Limpieza de canalones con retirada de hojas, barro, musgo y residuos. Revisión de bajantes, uniones y evacuación antes de valorar reparaciones.',h1:'Limpieza de canalones',lead:'Retirar residuos no consiste solo en vaciar lo visible. Conviene comprobar también entradas de bajante, codos accesibles, uniones y puntos donde el agua puede quedar retenida.',sections:[
    ['Qué se revisa','Suciedad acumulada, salida hacia la bajante, juntas visibles, fijaciones y puntos de rebose. Si el problema no es suciedad, se diferencia antes de proponer una reparación.'],
    ['Cuándo conviene actuar','Cuando el agua rebosa, aparecen plantas o musgo, se observan goteos en juntas o la bajante evacua con lentitud.'],
    ['Qué ayuda a valorar','Tipo de inmueble, altura aproximada, acceso y fotografías tomadas desde una zona segura.']
  ]},
  {slug:'limpieza-tejados',title:'Limpieza de tejados',desc:'Limpieza de tejados y cubiertas según material y estado. Valoración previa de suciedad, musgo, remates, tejas y método de limpieza adecuado.',h1:'Limpieza de tejados y cubiertas',lead:'No todas las cubiertas deben limpiarse de la misma forma. El material, la pendiente, el estado de las tejas y el tipo de suciedad condicionan el método adecuado.',sections:[
    ['Antes de limpiar','Se revisa visualmente el estado de la cubierta, tejas desplazadas o rotas, remates y zonas especialmente expuestas.'],
    ['Suciedad habitual','Musgo, materia orgánica, polvo y restos que se acumulan con el tiempo. La actuación debe adaptarse al soporte para evitar daños innecesarios.'],
    ['Después de la limpieza','Puede ser útil comprobar canalones y puntos de evacuación para evitar que los residuos desplazados terminen provocando atascos.']
  ]},
  {slug:'desatasco-bajantes',title:'Desatasco de bajantes',desc:'Desatasco de bajantes y codos cuando el canalón rebosa o el agua evacua lentamente. Comprobación del recorrido y puntos de obstrucción.',h1:'Desatasco de bajantes',lead:'Cuando el canalón parece limpio pero el agua sigue acumulándose, la obstrucción puede estar en la entrada de la bajante, un codo o el tramo vertical.',sections:[
    ['Señales de atasco','Agua retenida, rebose junto a la bajante, ruido de evacuación irregular o descarga muy lenta.'],
    ['Qué se comprueba','Entrada, codos accesibles y recorrido visible. El objetivo es localizar el punto del problema antes de desmontar o sustituir piezas.'],
    ['Prevención','Mantener el canalón libre de hojas y residuos reduce la cantidad de material que termina entrando en la bajante.']
  ]},
  {slug:'reparacion-goteras',title:'Reparación de goteras',desc:'Revisión y reparación localizada de goteras en tejados, encuentros y remates. Identificación del punto de entrada de agua antes de intervenir.',h1:'Reparación de goteras y filtraciones',lead:'Una mancha interior no siempre coincide exactamente con el punto por el que entra el agua. Conviene revisar tejas, encuentros, limas, remates y sellados próximos.',sections:[
    ['Localizar antes de reparar','Se parte de los síntomas visibles y se revisan los puntos de entrada más probables, evitando sellados generales sin diagnóstico previo.'],
    ['Problemas frecuentes','Tejas rotas o desplazadas, encuentros deteriorados, remates abiertos y pequeños fallos de impermeabilización.'],
    ['Urgencias 24 h','Si la entrada de agua está activa, indica localidad, tipo de inmueble y dónde aparece la humedad. Las fotografías desde una zona segura ayudan a preparar el aviso.']
  ]},
  {slug:'impermeabilizacion-tejados',title:'Impermeabilización de tejados',desc:'Impermeabilización localizada de tejados, encuentros, chimeneas y remates expuestos a filtraciones. Revisión previa del origen del problema.',h1:'Impermeabilización de tejados y remates',lead:'Impermeabilizar tiene sentido cuando se conoce la zona que necesita protección. Aplicar productos sin localizar el origen puede ocultar el problema sin resolverlo.',sections:[
    ['Zonas habituales','Encuentros con paramentos, chimeneas, remates, pequeñas fisuras y puntos expuestos donde se ha deteriorado el sellado.'],
    ['Valoración previa','Se comprueba si el problema procede realmente de impermeabilización o de una teja, unión o elemento que necesita otro tipo de reparación.'],
    ['Mantenimiento','La revisión periódica de remates y encuentros ayuda a detectar deterioros antes de que aparezcan filtraciones interiores.']
  ]}
];
const servicePage=s=>`${head(`${s.title} | Canalones y Tejados`,s.desc,`/${s.slug}/`,'España')}<body>${header()}<main><div class="wrap crumbs"><a href="/">Inicio</a> → ${E(s.title)}</div><section class="local-hero service-hub-hero"><div class="wrap"><span class="eyebrow">Servicio especializado</span><h1>${E(s.h1)}</h1><p class="lead2">${E(s.lead)}</p>${contact()}</div></section><section class="section wrap"><div class="intent-grid service-hub-grid">${s.sections.map(([title,text])=>`<article><h2>${E(title)}</h2><p>${E(text)}</p></article>`).join('')}</div><div class="service-hub-note"><h2>Consulta desde tu pueblo</h2><p>La cobertura está organizada por provincia y municipio. Puedes buscar tu localidad desde la portada y abrir el aviso con el pueblo ya preparado.</p><a class="btn" href="/#pueblos">Buscar mi pueblo</a></div></section></main>${footer()}</body></html>`;

const legalLinks='<a href="/aviso-legal/">Aviso legal</a> · <a href="/privacidad/">Privacidad</a> · <a href="/cookies/">Cookies</a> · <button type="button" class="footer-cookie-link" data-cookie-open>Configurar cookies</button>';
const cookieUi=()=>`<div class="cookie-banner" data-cookie-banner hidden><div><strong>Privacidad y cookies</strong><p>Usamos almacenamiento local para recordar tu elección. Las cookies o tecnologías no necesarias solo se activarían con tu consentimiento.</p><a href="/cookies/">Ver política de cookies</a></div><div class="cookie-actions"><button type="button" class="cookie-btn secondary" data-cookie-reject>Rechazar</button><button type="button" class="cookie-btn" data-cookie-accept>Aceptar</button></div></div><dialog class="cookie-dialog" data-cookie-dialog><form method="dialog"><button class="cookie-close" aria-label="Cerrar">×</button><h2>Preferencias de cookies</h2><div class="cookie-row"><div><strong>Necesarias</strong><p>Permiten funciones básicas y recordar tus preferencias.</p></div><span>Siempre activas</span></div><div class="cookie-row"><div><strong>Analíticas</strong><p>No se cargan actualmente. Si se incorporan en el futuro, requerirán consentimiento.</p></div><label><input type="checkbox" data-cookie-analytics> Permitir</label></div><div class="cookie-actions"><button type="button" class="cookie-btn secondary" data-cookie-save>Guardar selección</button><button type="button" class="cookie-btn" data-cookie-all>Aceptar todas</button></div><p class="fine">Puedes cambiar esta elección en cualquier momento desde “Configurar cookies” en el pie de página.</p></form></dialog>`;
const legalPage=(slug,title,body)=>`${head(`${title} | Limpieza Canalones y Tejados`,title,`/${slug}/`,'España')}<body>${header()}<main><div class="wrap crumbs"><a href="/">Inicio</a> → ${E(title)}</div><section class="section wrap legal-page"><span class="eyebrow">Información legal</span><h1>${E(title)}</h1>${body}</section></main>${footer()}</body></html>`;

const write=(route,html)=>{const d=route==='/'?out:path.join(out,route.replace(/^\//,'').replace(/\/$/,''));fs.mkdirSync(d,{recursive:true});fs.writeFileSync(path.join(d,'index.html'),html)};
function home(){const title='Limpieza de canalones y tejados | Urgencias 24 h',desc='Limpieza y reparación de canalones y tejados, bajantes, goteras, impermeabilización y urgencias 24 h. Servicio organizado por provincias y pueblos.',provs=site.provinces.map(p=>`<a class="province" href="/${p.slug}/"><strong>${E(p.name)}</strong><span>${data.groups[p.slug].length} municipios</span></a>`).join(''),featured=site.provinces.map(p=>{const a=data.groups[p.slug],take=Math.min(14,a.length),picked=Array.from({length:take},(_,i)=>a[Math.floor(i*(a.length-1)/Math.max(1,take-1))]);return`<article class="town-province"><div class="town-province-head"><h3>${E(p.name)}</h3><a href="/${p.slug}/">Ver todos</a></div><div class="home-town-links">${picked.map(x=>`<a href="/${p.slug}/${S(x.name)}/">Limpieza de canalones en ${E(x.name)}</a>`).join('')}</div></article>`}).join('');return`${head(title,desc,'/','España')}<body>${header()}<main>
<section class="hero"><div class="wrap hero-grid"><div><span class="eyebrow">Canalones · Tejados · Bajantes · Goteras</span><h1>Limpieza de canalones y tejados cerca de tu pueblo</h1><p class="lead">Retirada de hojas y suciedad, desatasco de bajantes, reparación de canalones, sustitución puntual de tejas rotas, goteras e impermeabilización de remates para mantener cubierta y evacuación en buen estado.</p>${contact()}<div class="trustline"><span class="stars" aria-label="cinco estrellas decorativas">★★★★★</span><span>Atención clara · trabajo ordenado · servicio local</span></div></div><div class="hero-art"><img src="https://images.pexels.com/photos/38867780/pexels-photo-38867780.jpeg?auto=compress&cs=tinysrgb&w=1200" alt="Operario realizando limpieza de tejado con agua a presión" width="620" height="430" loading="eager" fetchpriority="high"></div></div></section>
<div class="strip"><div class="wrap"><span>Limpieza de hojas y barro</span><span>Desatasco de bajantes</span><span>Tejas y goteras</span><span>Impermeabilización y remates</span></div></div>
<section class="section wrap" id="servicios"><span class="eyebrow">Servicios</span><h2>Canalones, bajantes y pequeñas reparaciones de tejado</h2><p class="lead2">No todos los problemas se resuelven cambiando piezas. Primero conviene distinguir entre suciedad, bajante obstruida, unión deteriorada, teja rota, gotera o un encuentro de cubierta que necesita sellado o impermeabilización.</p>${cards()}</section>
<section class="section visual-section"><div class="wrap"><span class="eyebrow">Trabajo sobre tejados y fachadas</span><h2>Qué suele encontrarse en un canalón con problemas</h2><div class="visual-grid"><article><img src="/assets/limpieza-hojas.svg" alt="Canalón con hojas y suciedad acumulada"><h3>Hojas, musgo y tierra</h3><p>La acumulación reduce la sección útil y puede provocar reboses cuando llueve con intensidad.</p></article><article><img src="/assets/bajante-atascada.svg" alt="Bajante atascada y agua acumulada"><h3>Bajantes obstruidas</h3><p>Si el canalón está limpio pero el agua no baja, el atasco puede estar en el codo o en el tubo vertical.</p></article><article><img src="/assets/reparacion-canalon.svg" alt="Reparación de unión y fijación de canalón"><h3>Uniones y fijaciones</h3><p>Goteos localizados, separaciones y pequeños movimientos pueden requerir sellado, ajuste o sustitución puntual.</p></article></div></div></section>
<section class="section wrap"><div class="split"><div><span class="eyebrow">Cuándo conviene revisar</span><h2>Señales de que el canalón necesita atención</h2><ul class="checklist"><li>El agua rebosa por encima del canalón.</li><li>La bajante traga lentamente o devuelve agua.</li><li>Aparecen goteos en juntas o esquinas.</li><li>Se ven hojas, plantas, musgo o barro acumulado.</li><li>Hay manchas de humedad cerca de aleros o fachada.</li><li>El canalón parece vencido, suelto o con poca pendiente.</li></ul></div><aside class="info-panel"><strong>Antes de reparar</strong><p>Conviene identificar dónde empieza el problema. Un atasco, una fuga o una fijación floja requieren soluciones distintas.</p><strong>Mantenimiento</strong><p>En zonas con árboles próximos, revisar periódicamente ayuda a detectar acumulaciones antes de que aparezcan reboses.</p></aside></div></section>
<section class="section soft"><div class="wrap"><span class="eyebrow">Cómo trabajamos</span><h2>Una intervención sencilla, explicada paso a paso</h2><div class="steps"><article><b>01</b><h3>Localizar el problema</h3><p>Canalón, unión, codo, bajante o punto de descarga.</p></article><article><b>02</b><h3>Limpiar y comprobar</h3><p>Retirada de residuos y comprobación del recorrido del agua.</p></article><article><b>03</b><h3>Reparar si hace falta</h3><p>Ajuste de pequeñas uniones, fijaciones o sellados deteriorados.</p></article><article><b>04</b><h3>Dejarlo preparado</h3><p>Recomendación de mantenimiento según entorno y acumulación.</p></article></div></div></section>
<section class="section wrap"><span class="eyebrow">Preguntas frecuentes</span><h2>Dudas habituales sobre limpieza y mantenimiento de canalones</h2><div class="faq"><details><summary>¿Cada cuánto conviene limpiar los canalones?</summary><p>Depende del entorno. Cerca de árboles o zonas con mucha hoja puede ser recomendable revisarlos con mayor frecuencia, especialmente antes de temporadas de lluvia intensa.</p></details><details><summary>¿Un canalón que rebosa siempre está roto?</summary><p>No. Muchas veces el problema está en hojas, barro o una bajante obstruida. La revisión previa evita sustituir piezas innecesariamente.</p></details><details><summary>¿Se puede reparar una fuga puntual?</summary><p>En algunos casos sí. Si la causa está en una unión, sellado o fijación concreta puede bastar una reparación localizada.</p></details><details><summary>¿Las mallas antihojas evitan todo el mantenimiento?</summary><p>No eliminan por completo la necesidad de revisión, pero pueden reducir la entrada de residuos grandes en determinados entornos.</p></details></div></section>
<section class="section soft" id="zonas"><div class="wrap"><span class="eyebrow">Cobertura por pueblos</span><h2>Limpieza de canalones organizada por provincia y municipio</h2><p class="lead2">Cada localidad dispone de su propia página para consultar limpieza, desatasco de bajantes, reparación y mantenimiento.</p><div class="province-grid">${provs}</div></div></section>
<section class="section wrap" id="pueblos"><span class="eyebrow">Pueblos y municipios</span><h2>Limpieza de canalones en pueblos de tu zona</h2><p class="lead2">Accede directamente a algunas de las localidades incluidas en nuestra cobertura. Cada página reúne limpieza de canalones, desatasco de bajantes, reparación y mantenimiento.</p><div class="home-town-groups">${featured}</div></section>\n<section class="section wrap" id="contacto"><span class="eyebrow">Consulta</span><h2>Cuéntanos qué ocurre en tu canalón o bajante</h2><p class="lead2">Indica localidad, tipo de inmueble, altura aproximada y si observas atasco, rebose, fuga o deterioro.</p>${contact()}</section>
</main>${footer()}</body></html>`}
function province(p){const ts=data.groups[p.slug].map(x=>({...x,slug:S(x.name)})),groups=new Map();for(const t of ts){const l=N(t.name)[0].toUpperCase();if(!groups.has(l))groups.set(l,[]);groups.get(l).push(t)}const title=`Limpieza de canalones y tejados en ${p.name} | Pueblos`,desc=`Limpieza de canalones y tejados, bajantes, goteras y mantenimiento en municipios de ${p.name}. Busca tu pueblo y consulta el servicio.`,list=[...groups].map(([l,a])=>`<section class="alpha-group"><h2>${l}</h2><div class="alpha">${a.map(t=>`<a href="/${p.slug}/${t.slug}/">Limpieza de canalones en ${E(t.name)}</a>`).join('')}</div></section>`).join('');return`${head(title,desc,`/${p.slug}/`,p.name)}<body>${header()}<main><div class="wrap crumbs"><a href="/">Inicio</a> → ${E(p.name)}</div><section class="local-hero"><div class="wrap"><span class="eyebrow">Directorio provincial</span><h1>Limpieza de canalones en ${E(p.name)}</h1><p class="lead2">Selecciona tu municipio para consultar limpieza, bajantes, reparación y mantenimiento.</p>${contact()}</div></section><section class="section wrap">${list}</section></main>${footer()}</body></html>`}
const intros=[n=>`La limpieza de canalones en ${n} se plantea según la suciedad acumulada, la evacuación de las bajantes y el acceso.`,n=>`En ${n}, conviene distinguir entre hojas acumuladas, una bajante obstruida o una unión que necesita reparación.`,n=>`Para organizar un servicio en ${n}, ayuda indicar tipo de inmueble, altura aproximada y dónde aparece el desbordamiento.`];
function town(t,p,i){const title=`Limpieza de canalones en ${t.name} | Bajantes y reparación`,desc=`Limpieza de canalones en ${t.name}, ${p.name}. Desatasco de bajantes, reparación, mallas antihojas y mantenimiento. Consulta servicio local.`,intro=intros[i%intros.length](t.name),arr=data.groups[p.slug],related=[1,2,3,4].map(d=>arr[(i+d)%arr.length]).map(x=>`<a href="/${p.slug}/${S(x.name)}/">Canalones en ${E(x.name)}</a>`).join(''),variant=i%4,caseText=[
`En viviendas con árboles próximos, hojas y pequeños restos pueden acumularse en codos y puntos bajos del canalón.`,
`Cuando el agua rebosa solo en un punto, conviene revisar primero la unión, la pendiente y la entrada de la bajante.`,
`Un goteo continuo puede proceder de una junta deteriorada, una fisura puntual o una fijación que ha cedido.`,
`Si el canalón parece limpio pero sigue sin evacuar, el problema puede encontrarse dentro de la bajante o en uno de sus codos.`
][variant];return`${head(title,desc,`/${p.slug}/${t.slug}/`,t.name)}<body>${header()}<main><div class="wrap crumbs"><a href="/">Inicio</a> → <a href="/${p.slug}/">${E(p.name)}</a> → ${E(t.name)}</div>
<section class="local-hero"><div class="wrap"><span class="eyebrow">Servicio de canalones en ${E(t.name)}</span><h1>Limpieza de canalones en ${E(t.name)}</h1><p class="lead2">${E(intro)}</p>${contact()}<div class="trustline local"><span class="stars" aria-hidden="true">★★★★★</span><span>Limpieza · bajantes · reparación · mantenimiento</span></div></div></section>
<section class="section wrap"><div class="local-grid"><div><h2>Canalones y bajantes en ${E(t.name)}</h2><p>Hojas, tierra, musgo y otros residuos pueden reducir el paso del agua. Antes de cambiar un canalón conviene localizar si el problema está en la suciedad acumulada, una unión, una fijación, la pendiente o la propia bajante.</p><p>${E(caseText)}</p></div><aside class="notice"><strong>Para preparar el aviso</strong><p>Indica localidad, tipo de inmueble, altura aproximada y si observas atasco, desbordamiento, fuga o una pieza suelta.</p></aside></div>${cards()}</section>
<section class="section soft"><div class="wrap"><h2>Problemas habituales que podemos revisar en ${E(t.name)}</h2><div class="intent-grid"><article><h3>Canalón que rebosa</h3><p>Puede existir acumulación de hojas, barro o una salida hacia la bajante parcialmente bloqueada.</p></article><article><h3>Bajante atascada</h3><p>Cuando el agua se queda retenida aunque el canalón esté limpio, conviene revisar codos y tubo vertical.</p></article><article><h3>Fugas y goteos</h3><p>Las juntas, tapas finales y uniones pueden deteriorarse y requerir una reparación localizada.</p></article><article><h3>Mantenimiento preventivo</h3><p>Una revisión periódica ayuda a detectar acumulaciones y pequeños defectos antes de que provoquen reboses.</p></article><article><h3>Tejas rotas y goteras</h3><p>Cuando la incidencia está en la cubierta, se revisan tejas desplazadas, fisuras visibles y puntos de entrada de agua.</p></article><article><h3>Impermeabilización y chimeneas</h3><p>Los encuentros de chimeneas, remates y zonas expuestas pueden requerir sellado o impermeabilización localizada.</p></article></div></div></section>
<section class="section wrap"><h2>Preguntas frecuentes sobre canalones en ${E(t.name)}</h2><div class="faq"><details><summary>¿Se puede limpiar sin sustituir el canalón?</summary><p>Sí, cuando el problema principal es acumulación de residuos o una obstrucción. Primero se revisa el estado general antes de proponer cambios.</p></details><details><summary>¿Qué datos ayudan a valorar el trabajo?</summary><p>Tipo de vivienda o edificio, altura aproximada, acceso y síntomas visibles: rebose, fuga, atasco o pieza suelta.</p></details><details><summary>¿También se revisan las bajantes?</summary><p>Sí, especialmente cuando el canalón está limpio pero el agua sigue sin evacuar correctamente.</p></details></div></section>
<section class="section soft"><div class="wrap"><h2>Otros municipios de ${E(p.name)}</h2><div class="towns">${related}</div><p><a href="/${p.slug}/"><strong>Ver todos los municipios de ${E(p.name)} →</strong></a></p></div></section>
<section class="section wrap" id="contacto"><h2>Consulta limpieza o reparación de canalones en ${E(t.name)}</h2><p class="lead2">Cuéntanos qué ocurre y dónde. Así resulta más fácil distinguir entre limpieza, desatasco, reparación o mantenimiento.</p>${contact()}</section></main>${footer()}</body></html>`}
write('/',home());for(const service of serviceHubs)write('/'+service.slug+'/',servicePage(service));let count=1+serviceHubs.length;
for(const p of site.provinces){write(`/${p.slug}/`,province(p));count++;data.groups[p.slug].forEach((x,i)=>{const t={...x,slug:S(x.name)};write(`/${p.slug}/${t.slug}/`,town(t,p,i));count++})}

write('/aviso-legal/',legalPage('aviso-legal','Aviso legal',`<h2>Titularidad del sitio</h2><p><strong>Responsable: RFG</strong></p><p>Dominio: <strong>limpiezacanalonesytejados.com</strong></p>${phone?`<p>Contacto: <a href="tel:${E(tel)}">${E(phone)}</a></p>`:''}<h2>Uso del sitio</h2><p>La información describe servicios de limpieza de canalones, tejados, bajantes, goteras y pequeñas reparaciones de cubierta. La información publicada no sustituye una valoración técnica del inmueble.</p><h2>Enlaces externos</h2><p>Los enlaces a servicios de terceros, como WhatsApp o proveedores de imágenes, quedan sujetos a sus propias condiciones y políticas.</p>`));
write('/privacidad/',legalPage('privacidad','Política de privacidad',`<h2>Responsable</h2><p><strong>RFG</strong></p>${phone?`<p>Contacto: <a href="tel:${E(tel)}">${E(phone)}</a></p>`:''}<h2>Qué datos se tratan</h2><p>La web no almacena en su propio formulario datos personales del visitante. El mini formulario prepara un mensaje que se abre en WhatsApp; el usuario decide si lo envía.</p><h2>Finalidad</h2><p>Los datos enviados voluntariamente por teléfono o WhatsApp se utilizan para atender consultas, preparar presupuestos y gestionar los servicios solicitados.</p><h2>Conservación y derechos</h2><p>Los datos se conservarán durante el tiempo necesario para atender la relación y cumplir las obligaciones aplicables. Puedes solicitar acceso, rectificación, supresión, oposición, limitación o portabilidad utilizando el canal de contacto disponible en esta web.</p><h2>Terceros</h2><p>Al usar WhatsApp o abrir recursos externos pueden intervenir proveedores ajenos a este sitio, sujetos a sus propias políticas.</p>`));
write('/cookies/',legalPage('cookies','Política de cookies',`<h2>Qué usamos ahora</h2><p>La web utiliza almacenamiento local del navegador para recordar la preferencia de cookies del usuario. No se cargan actualmente cookies analíticas o publicitarias propias del sitio.</p><h2>Cookies técnicas o necesarias</h2><p>Las tecnologías estrictamente necesarias permiten el funcionamiento básico y no requieren la misma base de consentimiento que las cookies de medición o publicidad.</p><h2>Cookies analíticas</h2><p>La categoría analítica queda preparada para futuras herramientas de medición, pero no debe activarse ningún proveedor analítico sin consentimiento previo cuando éste sea necesario.</p><h2>Cómo cambiar la elección</h2><p>El usuario puede volver a abrir el panel desde “Configurar cookies” en el pie de página. También puede gestionar cookies desde la configuración de su navegador.</p>`));

fs.writeFileSync(out+'/404.html',`${head('Página no encontrada | Limpieza Canalones y Tejados','Página no encontrada.','/404','España')}<body>${header()}<main class="section wrap"><h1>Página no encontrada</h1><a class="btn" href="/">Volver al inicio</a></main>${footer()}</body></html>`);
const urls=[...serviceHubs.map(s=>U('/'+s.slug+'/')),U('/aviso-legal/'),U('/privacidad/'),U('/cookies/')];for(const p of site.provinces){urls.push(U('/'+p.slug+'/'));for(const x of data.groups[p.slug])urls.push(U('/'+p.slug+'/'+S(x.name)+'/'))}urls.unshift(U('/'));
if(prod){const by=new Map([['core',[U('/'),...serviceHubs.map(s=>U('/'+s.slug+'/')),U('/aviso-legal/'),U('/privacidad/'),U('/cookies/')]]]);for(const p of site.provinces)by.set(p.slug,[U('/'+p.slug+'/'),...data.groups[p.slug].map(x=>U('/'+p.slug+'/'+S(x.name)+'/'))]);fs.mkdirSync(out+'/sitemaps',{recursive:true});const children=[];for(const[k,a]of by){const n='sitemap-'+k+'.xml';fs.writeFileSync(out+'/sitemaps/'+n,`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${a.map(u=>`<url><loc>${u}</loc></url>`).join('')}</urlset>`);children.push(U('/sitemaps/'+n))}fs.writeFileSync(out+'/sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${children.map(u=>`<sitemap><loc>${u}</loc></sitemap>`).join('')}</sitemapindex>`);fs.writeFileSync(out+'/robots.txt',`User-agent: *\nAllow: /\n\nSitemap: ${U('/sitemap.xml')}\n`)}else fs.writeFileSync(out+'/robots.txt','User-agent: *\nDisallow: /\n');
fs.writeFileSync(out+'/manifest.json',JSON.stringify({mode:prod?'production':'preview',towns:Object.values(data.groups).reduce((n,a)=>n+a.length,0),provinces:site.provinces.length,urls:urls.length},null,2));
console.log(`BUILD OK: ${urls.length} URLs + 404; modo=${prod?'production':'preview'}`);
