import fs from'node:fs';import path from'node:path';import site from'../config/site.json'with{type:'json'};
const prod=process.env.BUILD_MODE==='production',domain=prod?process.env.SITE_DOMAIN:site.previewDomain,phone=prod?process.env.SITE_PHONE:'',tel=prod?process.env.SITE_TEL:'',wa=prod?process.env.SITE_WHATSAPP:'';
if(prod&&(!domain||!phone||!tel||!wa))throw Error('Producción requiere SITE_DOMAIN, SITE_PHONE, SITE_TEL y SITE_WHATSAPP');
const data=JSON.parse(fs.readFileSync('.cache/municipios.json','utf8')),out='dist';fs.rmSync(out,{recursive:true,force:true});fs.mkdirSync(out,{recursive:true});fs.mkdirSync(out+'/assets',{recursive:true});
for(const f of ['site.css','site.js'])fs.copyFileSync('src/'+f,out+'/assets/'+f);fs.copyFileSync('src/hero-canalones.svg',out+'/assets/hero-canalones.svg');
const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),N=s=>String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase(),S=s=>N(s).replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''),U=r=>new URL(r,domain.endsWith('/')?domain:domain+'/').href;
const logo='<span class="brand"><svg viewBox="0 0 72 58" aria-hidden="true"><path d="M8 22h48v11H8zM12 33h40v13H12z" fill="none" stroke="currentColor" stroke-width="4"/><path d="M56 27v20c0 5 4 9 9 9" fill="none" stroke="currentColor" stroke-width="6" stroke-linecap="round"/><path d="m15 18 12-9 13 9" fill="none" stroke="currentColor" stroke-width="4"/></svg><span>CANALONES<br>LIMPIOS<small>Limpieza · Bajantes · Mantenimiento</small></span></span>';
const contact=()=>phone?`<div class="actions"><a class="btn" href="tel:${E(tel)}">☎ ${E(phone)}</a><a class="btn light" href="https://wa.me/${E(wa)}">WhatsApp</a></div>`:'<div class="actions"><a class="btn" href="#contacto">Consultar servicio</a></div>';
const header=()=>`${prod?'':'<div class="preview">VISTA PREVIA · indexación bloqueada hasta aprobar dominio y teléfono</div>'}<div class="top"><div class="wrap"><span>Limpieza y mantenimiento de canalones</span><span>Servicio organizado por pueblos</span></div></div><header><div class="wrap head"><a href="/">${logo}</a><nav class="nav"><a href="/#servicios">Servicios</a><a href="/#zonas">Provincias</a><a href="/#contacto">Contacto</a></nav></div></header>`;
const footer=()=>`<footer class="footer"><div class="wrap footer-grid"><div><strong>Canalones Limpios</strong><p>Limpieza, desatasco y mantenimiento de canalones y bajantes.</p></div><div><strong>Provincias</strong><p>${site.provinces.map(p=>`<a href="/${p.slug}/">${E(p.name)}</a>`).join(' · ')}</p></div><div><strong>Contacto</strong><p>${phone?E(phone):'Pendiente de publicar'}</p></div></div></footer>${phone?`<div class="mobilebar"><a href="tel:${E(tel)}">☎ ${E(phone)}</a><a href="https://wa.me/${E(wa)}">WhatsApp</a></div>`:''}`;
const head=(title,desc,route,area)=>`<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>${E(title)}</title><meta name="description" content="${E(desc)}"><meta name="robots" content="${prod?'index,follow':'noindex,nofollow'}"><link rel="canonical" href="${E(U(route))}"><meta property="og:title" content="${E(title)}"><meta property="og:description" content="${E(desc)}"><meta property="og:url" content="${E(U(route))}"><meta name="theme-color" content="#176b4d"><link rel="stylesheet" href="/assets/site.css"><script src="/assets/site.js" defer></script><script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@graph':[{'@type':'WebPage',name:title,url:U(route)},{'@type':'Service',name:'Limpieza y mantenimiento de canalones',areaServed:{'@type':'AdministrativeArea',name:area},provider:{'@type':'Organization',name:'Canalones Limpios',url:U('/')}}]})}</script></head>`;
const services=[['Limpieza de canalones','Retirada de hojas, tierra, musgo y residuos acumulados.'],['Desatasco de bajantes','Revisión cuando el agua no evacua correctamente.'],['Reparación de canalones','Uniones, fijaciones, pequeñas fugas y tramos deteriorados.'],['Mantenimiento preventivo','Limpiezas periódicas para reducir atascos y desbordamientos.'],['Mallas antihojas','Protectores cuando el entorno provoca acumulaciones frecuentes.'],['Revisión relacionada','Comprobación visual del entorno del canalón durante el acceso.']];
const cards=()=>`<div class="services">${services.map(x=>`<article class="card"><b>${x[0]}</b><p>${x[1]}</p></article>`).join('')}</div>`;
const write=(route,html)=>{const d=route==='/'?out:path.join(out,route.replace(/^\//,'').replace(/\/$/,''));fs.mkdirSync(d,{recursive:true});fs.writeFileSync(path.join(d,'index.html'),html)};
function home(){const title='Canalones Limpios | Limpieza de canalones en tu pueblo',desc='Limpieza, desatasco, reparación y mantenimiento de canalones y bajantes. Servicio organizado por provincia y municipio.',provs=site.provinces.map(p=>`<a class="province" href="/${p.slug}/"><strong>${E(p.name)}</strong><span>${data.groups[p.slug].length} municipios</span></a>`).join('');return`${head(title,desc,'/','España')}<body>${header()}<main><section class="hero"><div class="wrap hero-grid"><div><span class="eyebrow">Canalones Limpios · Servicio local</span><h1>Limpieza de canalones en tu pueblo</h1><p class="lead">Limpieza, desatasco y mantenimiento de canalones y bajantes en viviendas, comunidades y pequeños edificios.</p>${contact()}</div><div class="hero-art"><img src="/assets/hero-canalones.svg" alt="Tejado con canalón limpio" width="620" height="430"></div></div></section><div class="strip"><div class="wrap"><span>Limpieza</span><span>Desatasco de bajantes</span><span>Reparación</span><span>Mantenimiento</span></div></div><section class="section wrap" id="servicios"><span class="eyebrow">Servicios</span><h2>Canalones y bajantes: mantener libre el recorrido del agua</h2><p class="lead2">Primero se identifica si el problema es suciedad, atasco, unión, fijación o bajante.</p>${cards()}</section><section class="section soft" id="zonas"><div class="wrap"><span class="eyebrow">Cobertura inicial</span><h2>Servicio organizado por provincias y pueblos</h2><div class="province-grid">${provs}</div></div></section><section class="section wrap" id="contacto"><h2>Consulta el servicio en tu localidad</h2>${contact()}</section></main>${footer()}</body></html>`}
function province(p){const ts=data.groups[p.slug].map(x=>({...x,slug:S(x.name)})),groups=new Map();for(const t of ts){const l=N(t.name)[0].toUpperCase();if(!groups.has(l))groups.set(l,[]);groups.get(l).push(t)}const title=`Limpieza de canalones en ${p.name} | Municipios`,desc=`Limpieza, desatasco y mantenimiento de canalones y bajantes en municipios de ${p.name}. Consulta tu localidad.`,list=[...groups].map(([l,a])=>`<section class="alpha-group"><h2>${l}</h2><div class="alpha">${a.map(t=>`<a href="/${p.slug}/${t.slug}/">Limpieza de canalones en ${E(t.name)}</a>`).join('')}</div></section>`).join('');return`${head(title,desc,`/${p.slug}/`,p.name)}<body>${header()}<main><div class="wrap crumbs"><a href="/">Inicio</a> → ${E(p.name)}</div><section class="local-hero"><div class="wrap"><span class="eyebrow">Directorio provincial</span><h1>Limpieza de canalones en ${E(p.name)}</h1><p class="lead2">Selecciona tu municipio para consultar limpieza, bajantes, reparación y mantenimiento.</p>${contact()}</div></section><section class="section wrap">${list}</section></main>${footer()}</body></html>`}
const intros=[n=>`La limpieza de canalones en ${n} se plantea según la suciedad acumulada, la evacuación de las bajantes y el acceso.`,n=>`En ${n}, conviene distinguir entre hojas acumuladas, una bajante obstruida o una unión que necesita reparación.`,n=>`Para organizar un servicio en ${n}, ayuda indicar tipo de inmueble, altura aproximada y dónde aparece el desbordamiento.`];
function town(t,p,i){const title=`Limpieza de canalones en ${t.name} | Canalones y bajantes`,desc=`Limpieza de canalones en ${t.name}, ${p.name}. Desatasco de bajantes, reparación y mantenimiento. Consulta el servicio local.`,intro=intros[i%intros.length](t.name),arr=data.groups[p.slug],related=[1,2,3,4].map(d=>arr[(i+d)%arr.length]).map(x=>`<a href="/${p.slug}/${S(x.name)}/">Canalones en ${E(x.name)}</a>`).join('');return`${head(title,desc,`/${p.slug}/${t.slug}/`,t.name)}<body>${header()}<main><div class="wrap crumbs"><a href="/">Inicio</a> → <a href="/${p.slug}/">${E(p.name)}</a> → ${E(t.name)}</div><section class="local-hero"><div class="wrap"><span class="eyebrow">Servicio en ${E(t.name)}</span><h1>Limpieza de canalones en ${E(t.name)}</h1><p class="lead2">${E(intro)}</p>${contact()}</div></section><section class="section wrap"><div class="local-grid"><div><h2>Canalones y bajantes en ${E(t.name)}</h2><p>Hojas, tierra y otros residuos pueden reducir el paso del agua. Antes de sustituir piezas conviene localizar si el problema está en el canalón, una unión o la bajante.</p></div><aside class="notice"><strong>Para preparar el aviso</strong><p>Indica localidad, tipo de inmueble, altura aproximada y si observas atasco, desbordamiento o fuga.</p></aside></div>${cards()}</section><section class="section soft"><div class="wrap"><h2>Otros municipios de ${E(p.name)}</h2><div class="towns">${related}</div><p><a href="/${p.slug}/"><strong>Ver todos →</strong></a></p></div></section><section class="section wrap" id="contacto"><h2>Consulta el servicio en ${E(t.name)}</h2>${contact()}</section></main>${footer()}</body></html>`}
write('/',home());let count=1;
for(const p of site.provinces){write(`/${p.slug}/`,province(p));count++;data.groups[p.slug].forEach((x,i)=>{const t={...x,slug:S(x.name)};write(`/${p.slug}/${t.slug}/`,town(t,p,i));count++})}
fs.writeFileSync(out+'/404.html',`${head('Página no encontrada | Canalones Limpios','Página no encontrada.','/404','España')}<body>${header()}<main class="section wrap"><h1>Página no encontrada</h1><a class="btn" href="/">Volver al inicio</a></main>${footer()}</body></html>`);
const urls=[];for(const p of site.provinces){urls.push(U('/'+p.slug+'/'));for(const x of data.groups[p.slug])urls.push(U('/'+p.slug+'/'+S(x.name)+'/'))}urls.unshift(U('/'));
if(prod){const by=new Map([['core',[U('/')]]]);for(const p of site.provinces)by.set(p.slug,[U('/'+p.slug+'/'),...data.groups[p.slug].map(x=>U('/'+p.slug+'/'+S(x.name)+'/'))]);fs.mkdirSync(out+'/sitemaps',{recursive:true});const children=[];for(const[k,a]of by){const n='sitemap-'+k+'.xml';fs.writeFileSync(out+'/sitemaps/'+n,`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${a.map(u=>`<url><loc>${u}</loc></url>`).join('')}</urlset>`);children.push(U('/sitemaps/'+n))}fs.writeFileSync(out+'/sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${children.map(u=>`<sitemap><loc>${u}</loc></sitemap>`).join('')}</sitemapindex>`);fs.writeFileSync(out+'/robots.txt',`User-agent: *\nAllow: /\n\nSitemap: ${U('/sitemap.xml')}\n`)}else fs.writeFileSync(out+'/robots.txt','User-agent: *\nDisallow: /\n');
fs.writeFileSync(out+'/manifest.json',JSON.stringify({mode:prod?'production':'preview',towns:urls.length-site.provinces.length-1,provinces:site.provinces.length,urls:urls.length},null,2));
console.log(`BUILD OK: ${count} páginas; modo=${prod?'production':'preview'}`);
